services:
  web-dev:
    image: ${IMAGE_NAME:-tocf-site-dev}
    build:
      context: .
      target: deps
    working_dir: /app
    command: npm run dev
    ports:
      - "${PORT_WEB:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    container_name: ${COMPOSE_PROJECT_NAME:-site-club-tesla}-site