services:
  web-dev:
    image: partenaires-web-dev
    build:
      context: .
      target: deps
    working_dir: /app
    command: npm run dev
    ports:
      - "${PORT_WEB:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules